In [1]:
import numpy as np
import pandas as pd

In [17]:
from tensorflow.keras import datasets

In [21]:
(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 5s 0us/step


In [25]:
x_test.shape

(10000, 28, 28)

In [29]:
x_train.shape

(60000, 28, 28)

In [31]:
width, height = 28, 28
input_shape = (width, height, 1)

In [35]:
input_shape

(28, 28, 1)

In [37]:
x_train = x_train.reshape(x_train.shape[0], width, height, 1)
x_test = x_test.reshape(x_test.shape[0], width, height, 1)

In [39]:
x_train.shape

(60000, 28, 28, 1)

In [41]:
y_train.shape

(60000,)

In [43]:
from sklearn.model_selection import train_test_split

In [45]:
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size = 0.1)

In [47]:
len(x_train)

54000

In [49]:
x_train = (x_train - x_train.mean()) / x_train.std()
x_val = (x_val - x_val.mean()) / x_val.std()
x_test = (x_test - x_test.mean()) / x_test.std()

In [51]:
x_train


array([[[[-0.42402061],
         [-0.42402061],
         [-0.42402061],
         ...,
         [-0.42402061],
         [-0.42402061],
         [-0.42402061]],

        [[-0.42402061],
         [-0.42402061],
         [-0.42402061],
         ...,
         [-0.42402061],
         [-0.42402061],
         [-0.42402061]],

        [[-0.42402061],
         [-0.42402061],
         [-0.42402061],
         ...,
         [-0.42402061],
         [-0.42402061],
         [-0.42402061]],

        ...,

        [[-0.42402061],
         [-0.42402061],
         [-0.42402061],
         ...,
         [-0.42402061],
         [-0.42402061],
         [-0.42402061]],

        [[-0.42402061],
         [-0.42402061],
         [-0.42402061],
         ...,
         [-0.42402061],
         [-0.42402061],
         [-0.42402061]],

        [[-0.42402061],
         [-0.42402061],
         [-0.42402061],
         ...,
         [-0.42402061],
         [-0.42402061],
         [-0.42402061]]],


       [[[-0.42402061],


In [53]:
y_train

array([6, 4, 9, ..., 3, 1, 0], dtype=uint8)

In [55]:
from tensorflow import keras

In [59]:
num_labels = 10

y_train = keras.utils.to_categorical(y_train)

In [61]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [63]:
y_val = keras.utils.to_categorical(y_val)
y_test = keras.utils.to_categorical(y_test)

###Model

In [77]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Input, Conv2D, MaxPooling2D, AveragePooling2D

In [81]:
model = Sequential()

model.add(Conv2D(6, kernel_size = (5, 5), strides = (1, 1), activation = 'tanh', input_shape = (28, 28, 1)))
model.add(AveragePooling2D(pool_size = (2, 2), strides = (1, 1)))
model.add(Conv2D(16, kernel_size = (5, 5), strides = (1, 1), activation = 'tanh'))
model.add(AveragePooling2D(pool_size = (2, 2), strides = (2, 2)))
model.add(Conv2D(120, kernel_size = (5, 5), strides = (1, 1), activation = 'tanh'))

model.add(Flatten())
model.add(Dense(84, activation = 'tanh'))
model.add(Dense(num_labels, activation = 'softmax'))

In [85]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_2 (Conv2D)                    │ (None, 24, 24, 6)           │             156 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ average_pooling2d (AveragePooling2D) │ (None, 23, 23, 6)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_3 (Conv2D)                    │ (None, 19, 19, 16)          │           2,416 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ average_pooling2d_1                  │ (None, 9, 9, 16)            │               0 │
│ (AveragePooling2D)                   │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_4 (Conv2D)                    │ (None, 5, 5, 120)           │          48,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 3000)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 84)                  │         252,084 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 10)                  │             850 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 303,626 (1.16 MB)

 Trainable params: 303,626 (1.16 MB)

 Non-trainable params: 0 (0.00 B)

In [87]:
model.compile(loss = keras.losses.categorical_crossentropy, optimizer = 'adam', metrics = ['accuracy'])

In [89]:
history = model.fit(x_train, y_train, batch_size = 32, epochs = 20, verbose = 1, validation_data = (x_val, y_val))

Epoch 1/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9023 - loss: 0.3134 - val_accuracy: 0.9678 - val_loss: 0.1020
Epoch 2/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9700 - loss: 0.1008 - val_accuracy: 0.9748 - val_loss: 0.0829
Epoch 3/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9767 - loss: 0.0778 - val_accuracy: 0.9758 - val_loss: 0.0774
Epoch 4/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9786 - loss: 0.0721 - val_accuracy: 0.9820 - val_loss: 0.0606
Epoch 5/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9796 - loss: 0.0638 - val_accuracy: 0.9748 - val_loss: 0.0794
Epoch 6/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9807 - loss: 0.0603 - val_accuracy: 0.9820 - val_loss: 0.0616
Epoch 7/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9822 - loss: 0.0566 - val_accuracy: 0.9813 - val_loss: 0.0613
Epoch 8/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9829 - loss: 0.0538 - 

In [91]:
score = model.evaluate(x_test, y_test, verbose = 1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9811 - loss: 0.0631


In [93]:
score

[0.051269665360450745, 0.9843999743461609]

In [97]:
!pip install pandoc

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for pandoc: filename=pandoc-2.4-py3-none-any.whl size=34820 sha256=72a92925638dd65ddf2ef54d8c2478c3ac144a80b532ffdee60e4533d8db2b02
  Stored in directory: c:\users\thushar\appdata\local\pip\cache\wheels\4f\d7\32\c6c9b7b05e852e920fd72174487be3a0f18e633a7adcc303be
Successfully built pandoc
